### ISSUE TITLE
Wrong snapping when moving groups/layers

### ISSUE THREAD

**Issue by quasado** [Gravit-io/gravit#234] opened 2014-12-29 10:04 UTC
Moving a group or layer actually tries to snap the shapes within the group / layer to themselves which is wrong as the whole group / layer should be snapped instead.

**Comment by anna-ignatenkova** [comment] 2015-01-04 21:54
Part of the issue is fixed by the commit ac3246a4344c57b804368df9ca94db00f4f76adc , which fixes correspondence between item selection and layer activation.

**Closed by anna-ignatenkova** 2015-01-04 21:54 UTC
Labels: bug
